

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloudmart-microservices-apps
  namespace: argocd
spec:
  description: cloudmart-microservices- applications on eks.

  # ✅ Allow BOTH app repo and gitops repo
  sourceRepos:
    - 'https://github.com/iam-alehaider/cloudmart-microservices-apps.git'
    - 'https://github.com/iam-alehaider/cloudmart-gitops.git'

  destinations:
    - namespace: cloudmart-microservices-apps
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'cert-manager.io'
      kind: ClusterIssuer

  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: 'apps'
      kind: Deployment
    - group: 'apps'
      kind: StatefulSet
    - group: 'networking.k8s.io'
      kind: Ingress
    - group: 'autoscaling'
      kind: HorizontalPodAutoscaler
    - group: 'policy'
      kind: PodDisruptionBudget

