

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-cart
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: cloudmart-microservices-apps

  sources:
    # ✅ Source 1: Helm chart from APP repo
    - repoURL: https://github.com/iam-alehaider/cloudmart-microservices-apps.git
      targetRevision: prod
      path: src/cart/chart
      helm:
        valueFiles:
          - $values/envs/prod/cart-values.yaml

    # ✅ Source 2: Values from GITOPS repo
    - repoURL: https://github.com/iam-alehaider/cloudmart-gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: cloudmart-microservices-apps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

